#!/usr/bin/python
import re
import sys
from subprocess import Popen, PIPE, STDOUT

# for labeling error messages w/ colors
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

linetypes = {
    "clang_error": "^\w*.c:\d+:\d+: error: (.*)$"
}

# making their file and gathering errors
cmd = "make " + sys.argv[1]
p = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=STDOUT, close_fds=True)
output = p.stdout.read()
outlines = output.split('\n')

for line in outlines:
    r = re.compile(linetypes["clang_error"])
    if (r.match(line) != None):
        print bcolors.OKBLUE + line + bcolors.ENDC
    